apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-auth
  namespace: mongodb
type: Opaque
data:
  # Username: admin
  username: YWRtaW4=
  # Password: MongoExpress123
  password: TW9uZ29FeHByZXNzMTIz
