apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual   # custom storage class
  hostPath:
    path: /root/data/mysql
    type: DirectoryOrCreate