apiVersion: v1
kind: Secret
metadata:
  name: redis-commander-auth
  namespace: redis
type: Opaque
data:
  # Username: admin
  username: YWRtaW4=
  # Password: RedisCommander123
  password: UmVkaXNDb21tYW5kZXIxMjM=
